-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.factions
(
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT factions_pkey PRIMARY KEY (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.factions
    OWNER to postgres;

GRANT ALL ON TABLE public.factions TO anon;

GRANT ALL ON TABLE public.factions TO authenticated;

GRANT ALL ON TABLE public.factions TO postgres;

GRANT ALL ON TABLE public.factions TO service_role;

CREATE TABLE IF NOT EXISTS public.units
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    faction text COLLATE pg_catalog."default" NOT NULL,
    base_size smallint,
    cost smallint NOT NULL,
    initiative smallint NOT NULL,
    defense smallint NOT NULL,
    resilience smallint NOT NULL,
    hit_points smallint NOT NULL,
    movement smallint NOT NULL,
    CONSTRAINT units_pkey PRIMARY KEY (id),
    CONSTRAINT units_faction_fkey FOREIGN KEY (faction)
        REFERENCES public.factions (name) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.units
    OWNER to postgres;

GRANT ALL ON TABLE public.units TO anon;

GRANT ALL ON TABLE public.units TO authenticated;

GRANT ALL ON TABLE public.units TO postgres;

GRANT ALL ON TABLE public.units TO service_role;
